abstract final class StringsManager {
  static const String startTitle = 'startTitle';
  static const String startDesc = 'startDesc';
  static const String language = 'language';
  static const String theme = 'theme';
  static const String letsStart = 'letsStart';

  static const String onTitle1 = 'on_title';
  static const String onDesc1 = 'on_description';
  static const String onTitle2 = 'on_title2';
  static const String onDesc2 = 'on_description2';
  static const String onTitle3 = 'on_title3';
  static const String onDesc3 = 'on_description3';

  static const String register = 'register';
  static const String name = 'name';
  static const String email = 'email';
  static const String password = 'password';
  static const String repassword = 'repassword';
  static const String createAccount = 'Create Account';
  static const String alreadyHaveAccount = 'Already Have Account ?';
  static const String login = "login";
  static const String dontHaveAccount = 'Don’t Have Account ?';
  static const String forgetPassword = 'Forget Password?';
  static const String resetPassword = 'Reset Password';
  static const String shouldnotempty = 'should not be empty';
  static const String Emailnotvaliad = 'Email not valiad';
  static const String passvaladetion = 'Password shoulnt be less than 8 char';
  static const String userNotFoundForEmail = 'No user found for that email';
  static const String ok = 'OK';
  static const String wrongPassword = 'Wrong password provided for that user.';
  static const String linksentsucessful = 'link sent sucessful';
  static const String passwordsDoNotMatch = 'Passwords do not match.';
  static const String weakPassword = 'The password provided is too weak.';
  static const String emailAlreadyInUse =
      'The account already exists for that email.';
  static const String selectGender = 'selectGender';
  static const String male = 'male';
  static const String female = 'female';
  static const String pleaseSelectGender = 'pleaseSelectGender';
  static const String birthday = 'This is a Birthday Party';
  static const String welcome = 'Welcome Back ✨';
  static const String createEvent = 'Create Event';
  static const String titel = 'Title';
  static const String eventtitle = ' Event Title';
  static const String desc = ' Description';
  static const String eventdesc = 'Event Description';
  static const String eventdate = 'Event Date';
  static const String choosedate = 'Choose Date';
  static const String eventtime = 'Event Time';
  static const String choosetime = 'Choose Time';
  static const String location = 'Location';
  static const String chooseeventlocation = 'Choose Event Location';
  static const String addevent = 'Add Event';
  static const String chooseeventdate = 'Choose Event Date';
  static const String chooseeventtime = 'Choose Event Time';
  static const String eventadded = 'Event Added Successfully';
  static const String search = 'Search For Event';
}
